### PR TITLE
New added Websites, FontAwesome Update and CleanUp

### PR DESCRIPTION
**Pull request by 4ndyZ**
I really like our project so I decided to contribute to it. I found at that there are many FontAwesome Icons which can be used to make everything look cleaner. So I startet to replace the images with them where possible. I also cleaned up the images folder.

FontAwesome
- Updated FontAwesome to Version 5.11.2
- Replaced icon images with FontAwesome icons when possible

CleanUp
- Deleted old no longer need images

New
- Added RocketChat
- Added Amazon Web Services (AWS)
- Added Battle.net (Blizzard)
- Added Heise online
- Added Odroid (Hardkernel)

### CODE REVIEW

**Comment by 4ndyZ** [comment]
Update: I also added Odroid (#13), Heise online and Battle.net

**Comment by 4ndyZ** [comment]
Update: I added Uplay, Cloudflare and Akamai and fixed the problem with the website not displaying the favicon

**Comment by vlcty** [comment]
Thanks! However I'd like to migrate away from fontawesome and use the real, official logos and link the permissions into the source.

**Comment by vlcty** [comment]
The FontAwesome stuff is broken. Any idea why?
Bildschirmfoto 2019-10-10 um 20 17 51

**Comment by vlcty** [comment]
Fixed in commit 97d397452b6b619ba306eab4ae3b107ed988b2a5
Downloaded FontAwesome again and used all.min.css as fontawesome.min.css.

**Comment by 4ndyZ** [comment]
> Fixed in commit [97d3974](https://github.com/vlcty/ipv6-overview.xyz/commit/97d397452b6b619ba306eab4ae3b107ed988b2a5)
> Downloaded FontAwesome again and used all.min.css as fontawesome.min.css.

For me it looks like there is some kind of bug in the FontAwesome CSS file because only their all.css and all.min.css work at the moment for me.

I overlooked that while testing.
Sorry for the hassel :/

**Comment by vlcty** [comment]
No problem. Hard to debug. Was more luck to be honest. That's why I want to get rid of it and use real images :-)
Thanks for the contribution!

**Pull request merged**
